[package]
name = "services"
version = "0.1.0"
edition = "2021"

[lib]
path = "./src/lib.rs"

[dependencies]
shared = { path = "../shared/" }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }

tokio = { workspace = true }
http-body-util = { workspace = true }
reqwest = { version = "0.12.9", features = ["json"] }

async-trait = {workspace = true}

tower = { workspace = true }
serde-env = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }

colored = { workspace = true }
chrono = { workspace = true }
sysinfo = { workspace = true }
form_urlencoded = { workspace = true }
multimap = { workspace = true }
lazy_static = { workspace = true }
toml = { workspace = true }
merge-struct ={ workspace = true }
clap = { workspace = true }
rand = { workspace = true }
queues = { workspace = true }
regex = { workspace = true }
bytes = { workspace = true }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[build-dependencies]
tonic-build = "0.12.1"
