[package]
name = "server"
version = "0.1.0"
edition = "2021"

[lib]
path = "./src/lib.rs"

[dependencies]
shared = { path = "../shared" }
services = { path = "../services" }
usecases = { path = "../usecases" }

tracing = {workspace = true}
tracing-subscriber = {workspace = true}

tokio = {workspace = true}
http-body-util = {workspace = true}

async-trait = {workspace = true}

tower = {workspace = true}
serde-env = {workspace = true}
serde_json = {workspace = true}
serde = {workspace = true}

colored = {workspace = true}
chrono = {workspace = true}
sysinfo = {workspace = true}
form_urlencoded = {workspace = true}
multimap = {workspace = true}
lazy_static = {workspace = true}
toml = {workspace = true}
merge-struct = {workspace = true}
clap = {workspace = true}
rand = {workspace = true}
queues = {workspace = true}

bytes = {workspace = true}
actix = "0.13.5"
actix-web = { version = "4.9.0", default-features = false, features = [
    "http2",
    "macros",
    "unicode",
] }
actix-ws = "0.3.0"
futures-util = "0.3.30"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
