[package]
name = "plugin_system"
version.workspace = true
edition.workspace = true

[dependencies]
shared = { path = "../shared/" }
macros = { path = "../macros/" }
plugin_api.path = "../../../plugin_api/"

libloading = "0.8.6"
tracing = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
tokio = {workspace = true}
lazy_static = {workspace = true}
derive_more = { version = "1.0.0", features = ["deref", "from", "into"] }
netcorehost = {version = "0.17.0", optional = true}

[features]
dotnet = ["netcorehost"]